from distutils.core import setup

setup(
    name="evc",
    packages=["evc"],  # this must be the same as the name above
    version="0.1",
    description="evc",
    author="kd",
    author_email="",
    keywords=["add", "sub", "tests"],
    classifiers=[],
    package_data={"static": ["index.html"]},
    install_requires=[
        "python-socketio",
        "pandas",
        "numpy",
        "tornado",
        "torch",
        "torchvision",
        "torchaudio",
        "scipy==1.13.1",
        "librosa==0.10.2",
        "pyyaml",
        "transformers",
        "hfutils",
        "huggingface-hub",
        "munch",
        "einops",
        "descript-audio-codec",
        # "gradio",
        "pydub",
        "resemblyzer",
        # "jiwer",
        # "FreeSimpleGUI",
        "soundfile",
        # "sounddevice",
        # "modelscope",
        # "funasr",
    ],
)
